# Generated by Django 4.2.2 on 2023-06-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Streamplatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("about", models.CharField(max_length=500)),
                ("website", models.URLField()),
            ],
        ),
        migrations.RenameModel(old_name="Movie", new_name="Watchlist",),
    ]
