# Generated by Django 4.2.2 on 2023-06-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0002_streamplatform_rename_movie_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Watchlist",
                to="watchlist.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
